BackOfficeBundle\Entity\Actions:
    type: entity
    table: actions
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        display:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        active:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
