BackOfficeBundle\Entity\Notification:
    type: entity
    table: notification
    indexes:
        notification_modified_by_fk:
            columns:
                - modified_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        broadcast:
            type: smallint
            nullable: true
            options:
                unsigned: false
                default: '1'
        modifiedAt:
            type: datetime
            nullable: false
            column: modified_at
    manyToOne:
        modifiedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                modified_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
