BackOfficeBundle\Entity\Post:
    type: entity
    table: post
    indexes:
        post_product_id_fk:
            columns:
                - product_id
        post_modified_by_user_fk:
            columns:
                - modified_by
        post_deleted_by_pk:
            columns:
                - deleted_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        threshold:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        link:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        active:
            type: smallint
            nullable: true
            options:
                unsigned: false
                default: '1'
        modifiedAt:
            type: datetime
            nullable: false
            column: modified_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        deletedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                deleted_by:
                    referencedColumnName: id
            orphanRemoval: false
        modifiedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                modified_by:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
